defaults:
  - base
  - _self_

use_text: false
use_image: true

model:
  module_name: models.openai
  class_name: MyOpenAI
  model: doubao-1.5-vision-pro-250328
  api_key: 
  base_url: https://ark.cn-beijing.volces.com/api/v3
  temperature: 0.3
  max_new_tokens: 8192

system_prompt: |
  You are an advanced image processing agent specialized in analyzing and extracting information from images. The images may include document screenshots, illustrations, or photographs. Your primary tasks include:
  Extracting textual information from images using Optical Character Recognition (OCR).
  Analyzing visual content to identify relevant details (e.g., objects, patterns, scenes).
  Combining textual and visual information to provide an accurate and context-aware answer to user's question.
  Remeber you can only get the information from the images provided, so maybe other agents can help you with the text information.
  Question: 